name: Ansible AWS Provisioner

on:
  workflow_dispatch:

jobs:
  provision-aws-resources:
    runs-on: ubuntu-latest
    
    # Define environment variables for the Ansible command
    env:
      ANSIBLE_PLAYBOOK_FILE: automate.yml
      
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      # Step 3: Install Ansible
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Execute AWS Playbook
        run: ansible-playbook ${{ env.ANSIBLE_PLAYBOOK_FILE }}